site_name: RNMR Documentation
theme: readthedocs

pages:
- Index: 'index.md'
- Getting Started: 'getting_started.md'
- Running Routine Experiments: 'running_routine_experiments.md'
- Macros: 'macros.md'

markdown_extensions:
    - toc:
        separator: "_"
